apiVersion: v1
kind: Service
metadata:
  name: gitops-backend
  namespace: default
  labels:
    app: gitops-backend
spec:
  selector:
    app: gitops-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
