apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-backend
  namespace: default
  labels:
    app: gitops-backend
spec:
  selector:
    matchLabels:
      app: gitops-backend
  replicas: 3 # Number of pod replicas
  strategy:
    rollingUpdate:
      maxSurge: 25% # Allows up to 25% more pods than desired during updates
      maxUnavailable: 25% # Allows up to 25% of pods to be unavailable during updates
    type: RollingUpdate # Update strategy
  template:
    metadata:
      labels:
        app: gitops-backend
    spec:
      containers:
      - name: gitops-backend
        image: adrf968/gitops-backend:13 # Image for the container
        ports:
        - containerPort: 3000 # Port exposed by the container
        env:
        - name: DB_USER
          value: "admin" # Database username
        - name: DB_PASSWORD
          value: "12345" # Database password (consider using Secrets)
        - name: DB_SERVER
          value: "wordpress-mysql.default.svc.cluster.local" # DNS name of the MySQL service
        - name: DB_DATABASE
          value: "user" # Name of the database to connect to
        - name: DB_PORT
          value: "3306" # Port for the database connection
